"use client"

// Mock database connection that simulates fetching from Supabase
// In a real implementation, this would connect to your Supabase database

export interface Worker {
  id: string
  full_name: string
  email: string
  phone: string
  whatsapp_number: string
  area: string
  age: number
  height: string
  dress_size: string
  top_size: string
  shoe_size: string
  instagram_handle: string | null
  tiktok_handle: string | null
  rating: number
  amount_owing: number
  work_contract_signed: boolean
  work_history: string
  notes_comments: string
  profile_pictures: string[] // Changed to array for multiple pictures
  created_at: string
  status: string
}

// All 20 workers from your database with multiple profile pictures
export const getAllWorkers = async (): Promise<Worker[]> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  return [
    {
      id: "1",
      full_name: "Hope",
      email: "hope@olivemind.com",
      phone: "068 027 5487",
      whatsapp_number: "068 027 5487",
      area: "CBD",
      age: 21,
      height: "1,60m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: "thee.pink.dove",
      tiktok_handle: "thee.pink.dove",
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Hope+Photo+1&bg=ff6b9d&color=white",
        "/placeholder.svg?height=300&width=300&text=Hope+Photo+2&bg=ff8fab&color=white",
        "/placeholder.svg?height=300&width=300&text=Hope+Photo+3&bg=ffb3c6&color=white",
      ],
      created_at: "2024-01-15",
      status: "active",
    },
    {
      id: "2",
      full_name: "Casey New",
      email: "casey@olivemind.com",
      phone: "072 028 4400",
      whatsapp_number: "072 028 4400",
      area: "Bluff",
      age: 19,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: null,
      tiktok_handle: null,
      rating: 4,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "New",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Casey+Photo+1&bg=4ecdc4&color=white",
        "/placeholder.svg?height=300&width=300&text=Casey+Photo+2&bg=6fd4cc&color=white",
      ],
      created_at: "2024-01-10",
      status: "active",
    },
    {
      id: "3",
      full_name: "Elihle",
      email: "elihle@olivemind.com",
      phone: "061 617 8929",
      whatsapp_number: "061 617 8929",
      area: "Kwamakhutha",
      age: 21,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: "elihlechamane",
      tiktok_handle: null,
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Elihle+Photo+1&bg=45b7d1&color=white",
        "/placeholder.svg?height=300&width=300&text=Elihle+Photo+2&bg=6bc5d8&color=white",
        "/placeholder.svg?height=300&width=300&text=Elihle+Photo+3&bg=91d3df&color=white",
      ],
      created_at: "2024-01-05",
      status: "active",
    },
    {
      id: "4",
      full_name: "Thando Sesami",
      email: "thando@olivemind.com",
      phone: "072 710 6369",
      whatsapp_number: "072 710 6369",
      area: "Kwamashu",
      age: 21,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "4",
      instagram_handle: "sesami.linqe",
      tiktok_handle: "sesami.linqe",
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Thando+Photo+1&bg=f7b731&color=white",
        "/placeholder.svg?height=300&width=300&text=Thando+Photo+2&bg=f9c74f&color=white",
      ],
      created_at: "2024-01-08",
      status: "active",
    },
    {
      id: "5",
      full_name: "Minehle New",
      email: "minehle@olivemind.com",
      phone: "071 444 0879",
      whatsapp_number: "071 444 0879",
      area: "CBD",
      age: 21,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: null,
      tiktok_handle: null,
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Minehle+Photo+1&bg=5f27cd&color=white",
        "/placeholder.svg?height=300&width=300&text=Minehle+Photo+2&bg=7c4ddb&color=white",
        "/placeholder.svg?height=300&width=300&text=Minehle+Photo+3&bg=9973e9&color=white",
      ],
      created_at: "2024-01-12",
      status: "active",
    },
    {
      id: "6",
      full_name: "Entle",
      email: "entle@olivemind.com",
      phone: "082 456 7818",
      whatsapp_number: "082 456 7818",
      area: "Kwamakhutha",
      age: 22,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: "entle_sn",
      tiktok_handle: null,
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: ["/placeholder.svg?height=300&width=300&text=Entle+Photo+1&bg=00d2d3&color=white"],
      created_at: "2024-01-14",
      status: "active",
    },
    {
      id: "7",
      full_name: "Hayley",
      email: "hayley@olivemind.com",
      phone: "079 729 6780",
      whatsapp_number: "079 729 6780",
      area: "Bluff",
      age: 21,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: "_amber_hayley_20",
      tiktok_handle: null,
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Hayley+Photo+1&bg=ff9ff3&color=white",
        "/placeholder.svg?height=300&width=300&text=Hayley+Photo+2&bg=ffb3f5&color=white",
        "/placeholder.svg?height=300&width=300&text=Hayley+Photo+3&bg=ffc7f7&color=white",
      ],
      created_at: "2024-01-16",
      status: "active",
    },
    {
      id: "8",
      full_name: "Khanya",
      email: "khanya@olivemind.com",
      phone: "081 748 0029",
      whatsapp_number: "081 748 0029",
      area: "PMB",
      age: 21,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: null,
      tiktok_handle: null,
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Khanya+Photo+1&bg=54a0ff&color=white",
        "/placeholder.svg?height=300&width=300&text=Khanya+Photo+2&bg=74b9ff&color=white",
      ],
      created_at: "2024-01-18",
      status: "active",
    },
    {
      id: "9",
      full_name: "Chantell",
      email: "chantell@olivemind.com",
      phone: "083 389 7435",
      whatsapp_number: "083 389 7435",
      area: "Pinetown",
      age: 25,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: null,
      tiktok_handle: null,
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Chantell+Photo+1&bg=2ed573&color=white",
        "/placeholder.svg?height=300&width=300&text=Chantell+Photo+2&bg=5de88a&color=white",
        "/placeholder.svg?height=300&width=300&text=Chantell+Photo+3&bg=8cfba1&color=white",
      ],
      created_at: "2024-01-20",
      status: "active",
    },
    {
      id: "10",
      full_name: "Amahle CBD",
      email: "amahle@olivemind.com",
      phone: "078 584 0383",
      whatsapp_number: "078 584 0383",
      area: "CBD",
      age: 22,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Medium",
      shoe_size: "5",
      instagram_handle: "amahlee_zaca",
      tiktok_handle: null,
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: ["/placeholder.svg?height=300&width=300&text=Amahle+Photo+1&bg=ffa502&color=white"],
      created_at: "2024-01-22",
      status: "active",
    },
    {
      id: "11",
      full_name: "Rachel",
      email: "rachel@olivemind.com",
      phone: "065 502 1290",
      whatsapp_number: "065 502 1290",
      area: "Bluff",
      age: 21,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: "_racheltheron",
      tiktok_handle: null,
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Rachel+Photo+1&bg=ff6348&color=white",
        "/placeholder.svg?height=300&width=300&text=Rachel+Photo+2&bg=ff7f69&color=white",
      ],
      created_at: "2024-01-24",
      status: "active",
    },
    {
      id: "12",
      full_name: "Thatho",
      email: "thatho@olivemind.com",
      phone: "062 418 9013",
      whatsapp_number: "062 418 9013",
      area: "Mount Edgecombe",
      age: 21,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: null,
      tiktok_handle: null,
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Thatho+Photo+1&bg=7bed9f&color=white",
        "/placeholder.svg?height=300&width=300&text=Thatho+Photo+2&bg=95f0b3&color=white",
        "/placeholder.svg?height=300&width=300&text=Thatho+Photo+3&bg=aff3c7&color=white",
      ],
      created_at: "2024-01-26",
      status: "active",
    },
    {
      id: "13",
      full_name: "Buhle Phindile",
      email: "buhle@olivemind.com",
      phone: "067 861 8515",
      whatsapp_number: "067 861 8515",
      area: "Umlazi",
      age: 21,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "4",
      instagram_handle: null,
      tiktok_handle: null,
      rating: 4,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: ["/placeholder.svg?height=300&width=300&text=Buhle+Photo+1&bg=70a1ff&color=white"],
      created_at: "2024-01-28",
      status: "active",
    },
    {
      id: "14",
      full_name: "Diana",
      email: "diana@olivemind.com",
      phone: "068 077 1361",
      whatsapp_number: "068 077 1361",
      area: "Bluff",
      age: 23,
      height: "1,55m",
      dress_size: "Medium",
      top_size: "Medium",
      shoe_size: "6",
      instagram_handle: "diana.gumede",
      tiktok_handle: "diana.gumede",
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Diana+Photo+1&bg=a4b0be&color=white",
        "/placeholder.svg?height=300&width=300&text=Diana+Photo+2&bg=b8c4d1&color=white",
        "/placeholder.svg?height=300&width=300&text=Diana+Photo+3&bg=ccd8e4&color=white",
      ],
      created_at: "2024-01-30",
      status: "active",
    },
    {
      id: "15",
      full_name: "Nomali",
      email: "nomali@olivemind.com",
      phone: "067 356 6256",
      whatsapp_number: "067 356 6256",
      area: "Kwamashu",
      age: 22,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: null,
      tiktok_handle: null,
      rating: 4,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Nomali+Photo+1&bg=ff7675&color=white",
        "/placeholder.svg?height=300&width=300&text=Nomali+Photo+2&bg=ff9191&color=white",
      ],
      created_at: "2024-02-01",
      status: "active",
    },
    {
      id: "16",
      full_name: "Sisanda MUT",
      email: "sisanda@olivemind.com",
      phone: "068 162 8874",
      whatsapp_number: "068 162 8874",
      area: "CBD",
      age: 21,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: "bxrbiem1",
      tiktok_handle: "bxrbiem1",
      rating: 4,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Sisanda+Photo+1&bg=fd79a8&color=white",
        "/placeholder.svg?height=300&width=300&text=Sisanda+Photo+2&bg=fd93ba&color=white",
        "/placeholder.svg?height=300&width=300&text=Sisanda+Photo+3&bg=fdadcc&color=white",
      ],
      created_at: "2024-02-03",
      status: "active",
    },
    {
      id: "17",
      full_name: "Nosipho Skha",
      email: "nosipho@olivemind.com",
      phone: "060 681 1020",
      whatsapp_number: "060 681 1020",
      area: "PMB",
      age: 26,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: null,
      tiktok_handle: null,
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: ["/placeholder.svg?height=300&width=300&text=Nosipho+Photo+1&bg=fdcb6e&color=white"],
      created_at: "2024-02-05",
      status: "active",
    },
    {
      id: "18",
      full_name: "Anele Inanda",
      email: "anele@olivemind.com",
      phone: "084 327 8875",
      whatsapp_number: "084 327 8875",
      area: "Inanda",
      age: 21,
      height: "1,65m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "5",
      instagram_handle: null,
      tiktok_handle: null,
      rating: 4,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Anele+Photo+1&bg=6c5ce7&color=white",
        "/placeholder.svg?height=300&width=300&text=Anele+Photo+2&bg=8b7aeb&color=white",
      ],
      created_at: "2024-02-07",
      status: "active",
    },
    {
      id: "19",
      full_name: "Yolanda New",
      email: "yolanda@olivemind.com",
      phone: "078 741 5842",
      whatsapp_number: "073 552 3258",
      area: "CBD",
      age: 23,
      height: "1,55m",
      dress_size: "Small",
      top_size: "Small",
      shoe_size: "4",
      instagram_handle: null,
      tiktok_handle: null,
      rating: 4,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Yolanda+Photo+1&bg=a29bfe&color=white",
        "/placeholder.svg?height=300&width=300&text=Yolanda+Photo+2&bg=b5afff&color=white",
        "/placeholder.svg?height=300&width=300&text=Yolanda+Photo+3&bg=c8c3ff&color=white",
      ],
      created_at: "2024-02-09",
      status: "active",
    },
    {
      id: "20",
      full_name: "Sanda Masuku",
      email: "sanda@olivemind.com",
      phone: "079 278 5703",
      whatsapp_number: "079 278 5703",
      area: "Kwamashu",
      age: 24,
      height: "1,55m",
      dress_size: "Medium",
      top_size: "Medium",
      shoe_size: "6",
      instagram_handle: null,
      tiktok_handle: null,
      rating: 5,
      amount_owing: 0.0,
      work_contract_signed: true,
      work_history: "NA",
      notes_comments: "Reliable, always punctual",
      profile_pictures: [
        "/placeholder.svg?height=300&width=300&text=Sanda+Photo+1&bg=3742fa&color=white",
        "/placeholder.svg?height=300&width=300&text=Sanda+Photo+2&bg=5b68fb&color=white",
      ],
      created_at: "2024-02-11",
      status: "active",
    },
  ]
}

export const addWorker = async (worker: Omit<Worker, "id" | "created_at" | "status">): Promise<Worker> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  const newWorker: Worker = {
    ...worker,
    id: Date.now().toString(),
    created_at: new Date().toISOString().split("T")[0],
    status: "active",
    profile_pictures:
      worker.profile_pictures && worker.profile_pictures.length > 0
        ? worker.profile_pictures
        : [`/placeholder.svg?height=300&width=300&text=${worker.full_name}&bg=74b9ff&color=white`],
  }

  return newWorker
}

export const updateWorker = async (id: string, updates: Partial<Worker>): Promise<Worker> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  const workers = await getAllWorkers()
  const worker = workers.find((w) => w.id === id)

  if (!worker) {
    throw new Error("Worker not found")
  }

  return { ...worker, ...updates }
}

export const deleteWorker = async (id: string): Promise<void> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  // In a real implementation, this would delete from the database
  console.log(`Deleting worker with id: ${id}`)
}
